**What is function transformer in machine learning?**

**The Function transformer is a tool in scikit-learn, a popular Python library for machine learning, that allows you to apply a specified function to the input data. The function transformer can be useful for performing custom transformations of input data in a machine learning pipeline**

The function Transformer  takes as input a single function that will be applied to each sample in the data, This function can be any Python function that takes a single argument, such as a lambda function or a user-defined function. The function should return the transformed sample.

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset
x = np.array([[1,2],[3,4]])

# define the transformation function
log_transform = FunctionTransformer(np.log1p)

# apply the transformation to the dataset
x_transformed = log_transform.transform(x)

# view the transformed data
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [ ]:
# Practical  usecases
# 1. Custom feature engineering

from sklearn.preprocessing import FunctionTransformer
import numpy as np

# Create a dataset
x = np.array([[1,2],[3,4]])

# define a custom feature engineering function
def sqr(x):
  return np.hstack((x,x**2))

# Create a FunctionTransformer to apply the custom function
custom_transformer = FunctionTransformer(sqr)

# apply the transformer to the input data
x_transformed = custom_transformer.transform(x)

print(x_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [ ]:
# 2. Scaling And Normalization

from sklearn.preprocessing import FunctionTransformer
import numpy as np

x = np.array([[1,2],[3,4]])

def my_scaling(x):
  return x/np.max(x)

custom_transformer = FunctionTransformer(my_scaling)

x_transformed = custom_transformer.transform(x)

print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [ ]:
x  = np.array([[1,2],[3,np.nan]])

def my_cleaning(x):
  x[np.isnan(x)] = 0
  return x

custom_transformer = FunctionTransformer(my_cleaning)

x_transformed = custom_transformer.transform(x)

print(x_transformed)

[[1. 2.]
 [3. 0.]]


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/placement - placement.csv')

In [ ]:
df.head(3)

,cgpa,resume_score,placed
0,8.14,6.52,1
1,6.17,5.17,0
2,8.27,8.86,1


In [ ]:
x = df.drop(columns=['placed'])
y = df['placed']

In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
log_transform = FunctionTransformer(np.log1p)

x_transformed = log_transform.transform(x)

In [ ]:
x_transformed

,cgpa,resume_score
0,2.212660,2.017566
1,1.969906,1.819699
2,2.226783,2.288486
3,2.064328,2.112635
4,2.142416,2.116256
...,...,...
95,1.991976,1.998774
96,2.222459,2.170196
97,2.034706,2.172476
98,2.212660,1.891605


In [ ]:
df = pd.read_csv('/content/insurance - insurance.csv')

In [ ]:
df.head()

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
df['sex'] = lb.fit_transform(df['sex'])
df['region']= lb.fit_transform(df['region'])

In [ ]:
df['smoker'] = lb.fit_transform(df['smoker'])

In [ ]:
df.dtypes

,0
age,int64
sex,int64
bmi,float64
children,int64
smoker,int64
region,int64
charges,float64


In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
log_transform = FunctionTransformer(np.log1p)

df_transformed = log_transform.transform(df)

In [ ]:
df_transformed

,age,sex,bmi,children,smoker,region,charges
0,2.995732,0.000000,3.363842,0.000000,0.693147,1.386294,9.734236
1,2.944439,0.693147,3.548755,0.693147,0.000000,1.098612,7.453882
2,3.367296,0.693147,3.526361,1.386294,0.000000,1.098612,8.400763
3,3.526361,0.693147,3.165686,0.000000,0.000000,0.693147,9.998137
4,3.496508,0.693147,3.397189,0.000000,0.000000,0.693147,8.260455
...,...,...,...,...,...,...,...
1333,3.931826,0.693147,3.464798,1.386294,0.000000,0.693147,9.268755
1334,2.944439,0.000000,3.494080,0.000000,0.000000,0.000000,7.699381
1335,2.944439,0.000000,3.633631,0.000000,0.000000,1.098612,7.396847
1336,3.091042,0.000000,3.288402,0.000000,0.000000,1.386294,7.605365


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/Attrition - Attrition (1).csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2


In [ ]:
df.dtypes

,0
Age,int64
Attrition,object
BusinessTravel,object
DailyRate,int64
Department,object
DistanceFromHome,int64
Education,int64
EducationField,object
EmployeeCount,int64
EmployeeNumber,int64


In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
a = pd.get_dummies(df,
                   columns=['Attrition','BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','Over18','OverTime'],
                   drop_first=True)
a = a.astype(int)

a

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0,0,0,0,0,1,0,0,1,1
1,49,279,8,1,1,2,3,61,2,2,...,0,0,0,0,1,0,0,1,0,0
2,37,1373,2,2,1,4,4,92,2,1,...,1,0,0,0,0,0,0,0,1,1
3,33,1392,3,4,1,5,4,56,3,1,...,0,0,0,0,1,0,0,1,0,1
4,27,591,2,1,1,7,1,40,3,1,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,1,0,0,0,0,0,0,1,0,0
1466,39,613,6,1,1,2062,4,42,2,3,...,0,0,0,0,0,0,0,1,0,0
1467,27,155,4,3,1,2064,2,87,4,2,...,0,0,1,0,0,0,0,1,0,1
1468,49,1023,2,3,1,2065,4,63,2,2,...,0,0,0,0,0,1,0,1,0,0


In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
def power(b):
  return b**2

custom = FunctionTransformer(power)

a_transform = custom.transform(a)

a_transform

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,1681,1214404,1,4,1,1,4,8836,9,4,...,0,0,0,0,0,1,0,0,1,1
1,2401,77841,64,1,1,4,9,3721,4,4,...,0,0,0,0,1,0,0,1,0,0
2,1369,1885129,4,4,1,16,16,8464,4,1,...,1,0,0,0,0,0,0,0,1,1
3,1089,1937664,9,16,1,25,16,3136,9,1,...,0,0,0,0,1,0,0,1,0,1
4,729,349281,4,1,1,49,1,1600,9,1,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,1296,781456,529,4,1,4247721,9,1681,16,4,...,1,0,0,0,0,0,0,1,0,0
1466,1521,375769,36,1,1,4251844,16,1764,4,9,...,0,0,0,0,0,0,0,1,0,0
1467,729,24025,16,9,1,4260096,4,7569,16,4,...,0,0,1,0,0,0,0,1,0,1
1468,2401,1046529,4,9,1,4264225,16,3969,4,4,...,0,0,0,0,0,1,0,1,0,0


In [ ]:
log = FunctionTransformer(np.log1p)

log_trans = log.transform(a)

log_trans

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,3.737670,7.005789,0.693147,1.098612,0.693147,0.693147,1.098612,4.553877,1.386294,1.098612,...,0.000000,0.0,0.000000,0.0,0.000000,0.693147,0.0,0.000000,0.693147,0.693147
1,3.912023,5.634790,2.197225,0.693147,0.693147,1.098612,1.386294,4.127134,1.098612,1.098612,...,0.000000,0.0,0.000000,0.0,0.693147,0.000000,0.0,0.693147,0.000000,0.000000
2,3.637586,7.225481,1.098612,1.098612,0.693147,1.609438,1.609438,4.532599,1.098612,0.693147,...,0.693147,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.693147,0.693147
3,3.526361,7.239215,1.386294,1.609438,0.693147,1.791759,1.609438,4.043051,1.386294,0.693147,...,0.000000,0.0,0.000000,0.0,0.693147,0.000000,0.0,0.693147,0.000000,0.693147
4,3.332205,6.383507,1.098612,0.693147,0.693147,2.079442,0.693147,3.713572,1.386294,0.693147,...,0.693147,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.693147,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,3.610918,6.785588,3.178054,1.098612,0.693147,7.631432,1.386294,3.737670,1.609438,1.098612,...,0.693147,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.693147,0.000000,0.000000
1466,3.688879,6.419995,1.945910,0.693147,0.693147,7.631917,1.609438,3.761200,1.098612,1.386294,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.693147,0.000000,0.000000
1467,3.332205,5.049856,1.609438,1.386294,0.693147,7.632886,1.098612,4.477337,1.609438,1.098612,...,0.000000,0.0,0.693147,0.0,0.000000,0.000000,0.0,0.693147,0.000000,0.693147
1468,3.912023,6.931472,1.098612,1.386294,0.693147,7.633370,1.609438,4.158883,1.098612,1.098612,...,0.000000,0.0,0.000000,0.0,0.000000,0.693147,0.0,0.693147,0.000000,0.000000
