In [ ]:
# Introduction to Numpy ------>
# Numpy is an open-source library that is used to handle scientific calculation

# Difference between list and numpy ------>
# 1. List is heterogenous || Numpy is homogeneous
# 2. list takes more memory || Numpy consumes less memory
# 3. List take more execution time || Numpy consumes less execution time

In [ ]:
# pip install numpy ---> for vs code
# !pip install numpy ---> for jupytr notebook
# uv add -r requirements.txt ---> for uv in vs code

In [ ]:
import numpy as np

In [ ]:
a=[1,2,3,4]
print(type(a))

<class 'list'>


In [ ]:
b=np.array(a)
b


array([1, 2, 3, 4])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
a=[]
size=int(input('Enter size:'))
for i in range(size):
  val=int(input('Enter item:'))
  a.append(val)

b=np.array(a)
b

Enter size:4
Enter item:12
Enter item:3
Enter item:45
Enter item:34


array([12,  3, 45, 34])

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [ ]:
# Matrix -- > rows and column

# row1=[1,2,3]
# row2=[4,5,6]
# row3=[7,8,9]

# col1=[1,4,7]
# col2=[2,5,8]
# col3=[3,6,9]


In [ ]:
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print('Total rows and columns:',b.shape)
print('Total elements in the array:',b.size)

Total rows and columns: (3, 3)
Total elements in the array: 9


In [ ]:
# How to check dimension of an matrix?

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
a=np.array([[3,4,5]])
a

array([[3, 4, 5]])

In [ ]:
a.ndim

2

In [ ]:
a=np.array([[[12,34,56]]])
a

array([[[12, 34, 56]]])

In [ ]:
a.ndim


3

In [ ]:
# Images--> pixel(0-255)--> normalize--> Matrix--> operations
# DL--> Artificial Neurons--> Weight--> Randomly creation--> Numpy
# Data sets--> Dummpy entry--> randome module--> attach pandas

In [ ]:
# Pre defined functions in numpy:

In [ ]:
# 1. Zeros--> It will create an array in which all the values will be 0 in either 1-D or multi dimension.

In [ ]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [ ]:
a=np.zeros([4,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 2. Ones--> It will create an array in which all the values will be 1 in either 1-D or multi dimension.

In [ ]:
a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [ ]:
a=np.array([4,4])
a

array([4, 4])

In [ ]:
# 3. eye() --> It will create an array in which digonal positional elements will be
# 1 and rest will be 0.


In [ ]:
a=np.eye(3) # Where rows == columns is known as Symmetric Matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.eye(3,4) # Where rows!=columns is known as Assymetric Matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#  4. diag()--> It will create an array in which we can set our custom values
# at digonal position.

In [ ]:
a=np.diag((1,23,45,67))
a

array([[ 1,  0,  0,  0],
       [ 0, 23,  0,  0],
       [ 0,  0, 45,  0],
       [ 0,  0,  0, 67]])

In [ ]:
# 5 . Random module-->
# (a). Randint()--> It will create an array randomly in a given range
# syntax : np.random.randint(min_range,max_range,total_numbers)

In [ ]:
a = np.random.randint(1,10,3)
a

array([2, 3, 8])

In [ ]:
# (b). rand()--> It will generate random numbers from 0-1
# syntax: np.random.rand(total_random_numbers)

In [ ]:
a=np.random.rand(4)
a

array([0.40037882, 0.09552888, 0.96848801, 0.55409106])

In [ ]:
# (c). seed
# dataset(emp_data)(emp_id,salary,domain)--> randomly column add(working_hours)

In [ ]:
# (c). seed --> It will fix or lock our generated data
# syntax: np.random.seed(45)
# a=np.random.randint(1,10,3)

In [ ]:
np.random.seed(55)
a=np.random.randint(1,10,3)
a

array([8, 9, 6])

In [ ]:
# View vs Copy

In [ ]:
a = np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
b=a[1:4]
b[:]=0
b

array([0, 0, 0])

In [ ]:
a

array([10,  0,  0,  0, 50, 60, 70, 80, 90])

In [ ]:
#copy

In [ ]:
a=np.array([10,20,30,40,50,60,70,80])
b=a[1:4].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
# Reshaping the array
# total rows * columns =total_elements

In [ ]:
a = np.random.randint(1,50,12)
a

array([38, 28, 34, 49, 36, 47, 31, 14, 31, 13, 25, 48])

In [ ]:
# 1*12 , 12*1
# 2*6,6*2
# 3*4 4*3

In [ ]:
a.reshape(2,6)

array([[38, 28, 34, 49, 36, 47],
       [31, 14, 31, 13, 25, 48]])

In [ ]:
a.reshape(3,4)

array([[38, 28, 34, 49],
       [36, 47, 31, 14],
       [31, 13, 25, 48]])

In [ ]:
# a.reshape(6,3) will give an error because it exceeds total elements

In [ ]:
# y = mx + b
# m = matrix --- weights
# x = values --> matrix

# matrix(columns) * row(matrix)

In [ ]:
a.shape


(12,)

In [ ]:
a.reshape(-1,3)

array([[38, 28, 34],
       [49, 36, 47],
       [31, 14, 31],
       [13, 25, 48]])

In [ ]:
a.reshape(2,-1)

array([[38, 28, 34, 49, 36, 47],
       [31, 14, 31, 13, 25, 48]])

In [ ]:
# Operations on Array

In [ ]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
# 1*5+2*7    1*6+2*8

In [ ]:
a.dot(b) # this is for matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [ ]:
b=a>10
a[b]

array([11, 12, 13, 14])

In [ ]:
a = np.arange(1,4)
a**2

array([1, 4, 9])

In [ ]:
a**3

array([ 1,  8, 27])

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(a)

np.int64(45)

In [ ]:
np.sum(a,axis=1)  # In numpy, axis = 1 means row wise operation

array([ 6, 15, 24])

In [ ]:
np.sum(a,axis=0)  # In numpy, axis = 0 means column wise operation

array([12, 15, 18])

In [ ]:
list = [1,2,3,4,5]
arr = np.array(list)
print(arr)
arr.ndim

[1 2 3 4 5]


1

In [ ]:
arr = np.random.randint(1,10,6).reshape(2,3)
arr

array([[6, 2, 7],
       [9, 1, 4]])

In [ ]:
arr = np.zeros([3,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones([3,3])
arr


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# Unique --> It will create an array in which it will remove duplicate values
# and it will return three arrays
# arr --> Unique elements of array
# return_index = True ---> Indexing of unique elements
# return_counts = True ---> Frequency of each elements

In [ ]:
a = np.array([1,2,3,4,4,3,2,4,4,4,5,4,6,6,5,7,7])
a

array([1, 2, 3, 4, 4, 3, 2, 4, 4, 4, 5, 4, 6, 6, 5, 7, 7])

In [ ]:
b = np.unique(a,return_index=True,return_counts=True)
b

(array([1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  1,  2,  3, 10, 12, 15]),
 array([1, 2, 2, 6, 2, 2, 2]))

In [ ]:
# Linspace()---> It will return an array in which elements will be in same gap in a given range

In [ ]:
arr = np.linspace(1,2,5)
arr

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Horizontal stacking vs Vertical stacking

In [ ]:
# Horizontal stacking---> It will add 2 or more arrays horizontally

In [ ]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [ ]:
c=np.arange(9,13)
c

array([ 9, 10, 11, 12])

In [ ]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Vertical stacking---> It will add 2 or more arrays vertically

In [ ]:
np.vstack([a,b,c])  # Vertical stack

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])